# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mnO8aBarrviwVS2FiPP2dK-cQ8ccK0Wk
"""



import streamlit as st
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

url = 'https://github.com/yosephine17vivi/airquality/blob/main/Dashboard/Data%20Air%20Quality.csv'
# Load the dataset
df = pd.read_csv(url)

# Convert the 'date' column to datetime type
df['date'] = pd.to_datetime(df['date'])

# Get the minimum and maximum dates
min_date = df['date'].min()
max_date = df['date'].max()

# Title of the page
st.title('Dashboard Analisis Data Air Quality')

# Sidebar for user inputs
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/1163/1163661.png")
    st.sidebar.write('**Nama:** Yosephine Paulina Sianipar')
    st.sidebar.write('**Email:** yosephsianipar17@gmail.com')
    st.sidebar.write('**ML-51**')
    
    # Date input selection
    start_date, end_date = st.date_input(
        label='Pilih Rentang Tanggal',
        value=[min_date, max_date],
        min_value=min_date,
        max_value=max_date
    )

# Filter data based on date range
filtered_data = df[(df['date'] >= pd.to_datetime(start_date)) & (df['date'] <= pd.to_datetime(end_date))]

# Display the filtered data
st.write("Data yang telah difilter berdasarkan rentang tanggal:")
st.dataframe(filtered_data)

# Visualize the data using a seaborn plot
st.subheader('Visualisasi Data Air Quality')
sns.set(style="whitegrid")
fig, ax = plt.subplots(figsize=(10, 6))
sns.lineplot(x='date', y='value', data=filtered_data, ax=ax)
st.pyplot(fig)
